CREATE TABLE IF NOT EXISTS `carts` (
    `_id` INT NOT NULL AUTO_INCREMENT UNIQUE,
    `cart_id` VARCHAR(250) NOT NULL UNIQUE,
    `user_id` VARCHAR(250) NULL UNIQUE,
    `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    `date_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY(cart_id),
    FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `cart_item` (
    `_id` INT NOT NULL AUTO_INCREMENT UNIQUE,
    `cart_item_id` VARCHAR(250) NOT NULL UNIQUE,
    `cart_id` VARCHAR(250) NOT NULL,
    `product_id` VARCHAR(250) NOT NULL DEFAULT '',
    `quantity` INT NOT NULL DEFAULT 1,
    `price` FLOAT NOT NULL DEFAULT 0.0,
    `date_created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    `date_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY(cart_item_id),
    FOREIGN KEY(product_id) REFERENCES products(product_id) ON DELETE CASCADE
);